# Ignore everything
*

# Allow files and directories
!context
!environments
!predictors
!cmd

# Ignore unnecessary files inside allowed directories
# This should go after theh allowed directories
# eg 
#**/*~,
#**/Thumbs.db, 
#**/*.log
context/local_debugging.py
**/.DS_Store,
**/__pycache__
**/-egg-info


