version: '3.9'
services:
  herg_ogura_random_forest:
    build:
      context: predictor_serving/images_v0/.
      dockerfile: Dockerfile.herg_ogura_rf
    ports:
    - "3002:5000"

  herg_ogura_feed_forward_network:
    build:
      context: predictor_serving/images_v0/.
      dockerfile: Dockerfile.herg_ogura_ffn
    ports:
    - "3003:5000"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "johan.broberg92@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "16543:80"
    depends_on:
      - db

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    depends_on:
      - "herg_ogura_random_forest"
      - "herg_ogura_feed_forward_network"
      - "db"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    ports:
      - "80:80"

volumes:
  db:
    driver: local