version: '3.9'
services:
  herg_ogura_random_forest:
    build:
      context: predictor_serving/images_v0/.
      dockerfile: Dockerfile.herg_ogura_rf

    ports:
    - "3002:5000"

  herg_ogura_feed_forward_network:
    build:
      context: predictor_serving/images_v0/.
      dockerfile: Dockerfile.herg_ogura_ffn
    ports:
    - "3003:5000"

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    depends_on:
      - "herg_ogura_random_forest"
      - "herg_ogura_feed_forward_network"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    ports:
      - "80:80"
