name: base-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - cudatoolkit=10.2
  - python=3.9
  - pip
  - numpy #=1.22
  - tqdm #=4.64
  #- rdkit #=2022.03.5
  - scikit-learn #=1.1.1
  - dill #=0.3
  - optuna #=2.10
  #- chembl_structure_pipeline=1.0.0
  - mordred #=1.2
  - flask #=2.2.2
  - flask-restful #=0.3.9
  - marshmallow #=3.17.1
  - requests #=2.28.1
  - gunicorn
  - pandas
  #- typing==3.7.4.3
