name: base-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=20.0
  - numpy=1.22
  - tqdm=4.64
  - scikit-learn=1.1.1
  - dill=0.3
  - optuna=2.10
  - mordred=1.2
  - flask=2.2.2
  - flask-restful=0.3.9
  - marshmallow=3.17.1
  - requests=2.28.1
  - gunicorn=20.1
  - pandas=1.4
  - pip:
     rdkit=2022.03.5
     
