name: rise-qsar-base
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - alembic=1.7.5
  - aniso8601=9.0.1
  - attrs=21.4.0
  - autopage=0.4.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - chembl_structure_pipeline=1.0.0
  - click=8.1.3
  - cliff=3.10.0
  - cmaes=0.8.2
  - cmd2=2.3.3
  - colorama=0.4.4
  - colorlog=6.6.0
  - cryptography=37.0.1
  - cycler=0.11.0
  - dill=0.3.4
  - flask-bcrypt=1.0.1
  - flask-restful=0.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.2
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.10.0
  - importlib_resources=5.4.0
  - itsdangerous=2.1.2
  - jbig=2.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - mako=1.1.6
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - mordred=1.2.0
  - munkres=1.1.4
  - ncurses=6.2
  - networkx=2.6.3
  - numpy=1.22.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.5
  - optuna=2.10.0
  - packaging=21.3
  - pandas=1.3.5
  - pbr=5.8.0
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - plotly=5.9.0
  - prettytable=3.0.0
  - pycairo=1.20.1
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.6
  - pyperclip=1.8.2
  - pysocks=1.7.1
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - rdkit=2021.09.3
  - readline=8.1
  - reportlab=3.5.68
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=60.5.0
  - six=1.16.0
  - sqlalchemy=1.4.29
  - sqlite=3.37.0
  - stevedore=3.5.0
  - tenacity=8.0.1
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tqdm=4.62.3
  - tzdata=2021e
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.1
  - pip:
    - blinker==1.5
    - dnspython==2.2.1
    - email-validator==1.2.1
    - flask==2.1.2
    - flask-login==0.6.2
    - flask-mail==0.9.1
    - flask-sqlalchemy==2.5.1
    - flask-wtf==1.0.1
    - gunicorn==20.1.0
    - pyjwt==2.5.0
    - python-dotenv==0.21.0
    - wtforms==3.0.1
